{{- if and .Values.pathCatalogue.enabled (not .Values.pathCatalogue.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workforce-management.fullname" . }}-path-catalogue
  labels:
    {{- include "workforce-management.labels" . | nindent 4 }}
data:
  process-paths.yaml: |
{{- .Values.pathCatalogue.content | nindent 4 }}
{{- end }}
